version: '3.7'

services:
  ex-elasticsearch:
    build:
      context: elk/elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: ex-elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - ex-elk

  ex-kibana:
    build:
      context: elk/kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: ex-kibana
    networks:
      - ex-elk
    depends_on:
      - ex-elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200

  ex-mongo-db:
    image: mongo:${MONGO_VERSION}
    container_name: ex-mongo-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      # seeding scripts
      - ./mongodb/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - ex-mongodb

  ex-mongo-client:
    # build will get tagged with 'image'
    build: ./mongodb/mongo-client
    image: mongo-client:3.9
    container_name: ex-mongo-client
    environment:
      - MONGO_SERVER=auth-mongo-db
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - ex-mongodb
    depends_on:
      - ex-mongo-db
      
  ex-mssql:
    build:
      context: mssql
    container_name: ex-mssql
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y

    volumes:
      - mssqlvolume:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"
      
  ex-mysql:
    build:
      context: mysql/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    container_name: ex-db-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-time-zone=Asia/Ho_Chi_Minh --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - $MYSQL_DEFAULT_PORT:3306
      
  ex-redis:
    build:
      context: redis/
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: ex-redis
    ports:
      - $REDIS_DEFAULT_PORT:6379
      
  ex-sonarqube:
    build:
      context: sonarqube
      args:
        SONAR_QUBE_VERSION: $SONAR_QUBE_VERSION
    container_name: ex-sonarqube
    ports:
      - $SONAR_QUBE_DEFAULT_PORT:9000
      - $SONAR_QUBE_EXTEND_PORT:9092
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs

networks:
  ex-elk:
    driver: bridge
  ex-mongodb:
    driver: bridge

volumes:
  elasticsearch-data:
  mongodb:
  mongoconfig:
  mssqlvolume:
  sonarqube-data:
  sonarqube-logs: