version: '3.8'

services:
  postgres:
    image: $PG_VERSION
    restart: always
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
