version: '3.8'

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: salvation_cb
      POSTGRES_USER: salvation
      POSTGRES_PASSWORD: Salvation2#!@
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
