version: '3.7'

services:  
  extension-mssql:
    build:
      context: mssql
    container_name: ex-mssql
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y

    volumes:
      - mssqlvolume:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"

volumes:
  mssqlvolume: